# Generated by Django 6.0.2 on 2026-03-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_time'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
    ]
