# Generated by Django 6.0.2 on 2026-03-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_news_views_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='views_count',
            new_name='view_count',
        ),
    ]
