# Generated by Django 6.0.2 on 2026-03-23 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_rename_views_count_news_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
    ]
